version: "3"

services:
  db:
    container_name: shkang_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: shkang_user
      MYSQL_PASSWORD: test1234!!
      MYSQL_MULTIPLE_DATABASES: user,place
    ports:
      - "3333:3306"
    volumes:
      - ./init_multi_databases.sh:/docker-entrypoint-initdb.d/init_multi_databases.sh
    networks:
      default:

  db-test:
    container_name: shkang_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: shkang_user
      MYSQL_PASSWORD: test1234!!
      MYSQL_MULTIPLE_DATABASES: user,place
    ports:
      - "3307:3306"
    volumes:
      - ./init_multi_databases.sh:/docker-entrypoint-initdb.d/init_multi_databases.sh
    networks:
      default:
