version: "3.5"
services:
  nats:
    container_name: nats
    entrypoint: '/nats-server -c nats-server.conf -DV'
    image: nats
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'

#networks:
#  nats:
#    name: nats